### ISSUE TITLE
Documentation link broken 

### ISSUE THREAD

**Issue by chrisk-7777** [chronark/highstorm#14]
Hi, I saw this project on Twitter, and wanted to give it a spin. 
Apologies if "Issues" is not the right spot. 

I've signed up for an account, however, when I drop onto the overview page nothing seems like it is enabled. 
I can't create an API key, or a team, it seems like all options are disabled? 

I tried visiting the docs from the account button bottom-left, but it leads to a 404. 
So I'm a bit lost on next steps or how to get it going. 

There _was_ an error during the signup flow after entering the verification number in the email, so I'm wondering if my account wasn't validated correctly?

Here are a couple of screenshots. The second is the docs page when I click the docs button

![CleanShot 2023-04-30 at 20 08 06](https://user-images.githubusercontent.com/55621012/235347660-b15e3ecf-e1d9-4448-9b4d-6003b7742374.png)

![CleanShot 2023-04-30 at 20 07 33](https://user-images.githubusercontent.com/55621012/235347659-478c5cc9-2226-4b02-a4ba-25dfc4c85856.png)

**Comment by chronark** [comment]
Oh dear, apologies.

I'll take a look in a couple of hours

**Comment by chronark** [comment]
Fixed a few things
creating teams is not yet supported in the UI, I'm working on that.
let me know and I'll create one manually for you

**Comment by chrisk-7777** [comment]
Nice, I can see the "create key" button now - thanks!
I'll give it a spin over the next few nights, cheers

**Comment by chronark** [comment]
Let me know what you think!
