### ISSUE TITLE
Can't get auth to work

### ISSUE THREAD

**Issue by sandervspl** [chronark/highstorm#17]
I believe I have everything set up. Planetscale is setup and working, Tinybird is setup, Clerk is setup and working. But, I'm running into issues with auth. After authorizing with Google I get sent back to `/overview` which loads for a bit but then throws me a 404 page. In the code I see that happens when a tenant cannot be found in the DB, and indeed my `tenant` table is empty.

There are no errors.

I can see that the Clerk webhook is working.

<img width="792" alt="Screenshot 2023-05-01 at 18 27 21" src="https://user-images.githubusercontent.com/4492636/235487699-477e0cee-24aa-451a-a00c-4d252be86f05.png">

<img width="785" alt="Screenshot 2023-05-01 at 18 27 37" src="https://user-images.githubusercontent.com/4492636/235487734-70279a81-77f2-40bf-9a61-52563b139718.png">

Does this look good? I'm not sure after looking at this and the docs.

**Comment by sandervspl** [comment]
Hmm, I changed the webhook URL to `/api/v1/clerk` and more is happening now. I've added a `HIGHSTORM_TOKEN` to env as well. It's just some random string with `api_` e.g. `api_foobar`. Is that right?

<img width="792" alt="Screenshot 2023-05-01 at 18 45 40" src="https://user-images.githubusercontent.com/4492636/235490422-5187fe63-8628-484d-af0e-e03437c4f09e.png">

The error I'm seeing in Vercel logs is this

```Error: Unable to ingest event: {"error":"Unauthorized"}
    at Highstorm.ingest (/var/task/apps/web/.next/server/pages/api/v1/clerk.js:313:15)```

**Comment by sandervspl** [comment]
Oh, I think I had to use GitHub sign in instead of Google 😅

**Comment by chronark** [comment]
so it worked in the end? :D

the `HIGHSTORM_TOKEN` is used to forward emit an event to the production highstorm app, I'll remove that, it's been tripping people up twice now :)

Also I'll make the webhook optional and instead upsert the tenant when they visit `/onboarding`. That's much cleaner and less to set up

**Comment by sandervspl** [comment]
Yes I got it all working now! Just not sure how I can log in on localhost because you can't use http for the webhook URL. Do you use something like ngrok to get a https url?

I could write up everything I had to do in a bit more detail if you want. Could be useful for other people!

**Comment by chronark** [comment]
yeah I used ngrok or just added my own user manually :D

yes, this would be great. if it's too long, maybe you can just start a `contributing.md` file. Don't worry about perfect styling, it just needs to help people get unstuck quickly.

**Comment by sandervspl** [comment]
Check! I will get started on it tonight. I will close this issue since It's been resolved
